### ISSUE TITLE
Trenger ikke denne.

### ISSUE THREAD

**Issue by crismo** [thomaseho/MegaUltraList#19]
https://github.com/thomaseho/MegaUltraList/blob/870a796b1d5e4e86e60ef860544df2ed7c8ea152/MegaUltraList/app/src/main/java/com/example/megaultralist/MainActivity.kt#L113

Du bruker ikke denne funksjonen så den kan med fordel slettes.

**Comment by thomaseho** [comment]
Den er nå slettet
