### ISSUE TITLE
Ikke sjekk inn utkomenterte ting av denne arten. 

### ISSUE THREAD

**Issue by crismo** [thomaseho/MegaUltraList#21]
https://github.com/thomaseho/MegaUltraList/blob/870a796b1d5e4e86e60ef860544df2ed7c8ea152/MegaUltraList/app/src/main/java/com/example/megaultralist/tasks/ToDoListDepositoryManager.kt#L47

**Comment by thomaseho** [comment]
Denne er nå fjernet
